# -*- coding: utf-8 -*-
"""sources/dr_universe.py — DR/DRx static mapping: underlying foreign stock → SET DR tickers"""

# DR / DRx static mapping — underlying foreign stock → Thai SET DR tickers
_DR_STATIC = [
    # ── United States ─────────────────────────────────────────────────────
    {"sym":'AAPL', "name":'Apple Inc.', "region":'US', "yf":"AAPL", "ind":'Consumer Electronics', "drs":["AAPL01", "AAPL03", "AAPL19", "AAPL80"]},
    {"sym":'APPL', "name":'AppLovin Corporation', "region":'US', "yf":"APP", "ind":'Mobile Advertising & AI', "drs":["APPL03"]},
    {"sym":'ABBV', "name":'AbbVie Inc.', "region":'US', "yf":"ABBV", "ind":'Biopharmaceuticals', "drs":["ABBV19", "ABBV80"]},
    {"sym":'ABNB', "name":'Airbnb, Inc.', "region":'US', "yf":"ABNB", "ind":'Travel & Hospitality', "drs":["ABNB06"]},
    {"sym":'ADBE', "name":'Adobe Inc.', "region":'US', "yf":"ADBE", "ind":'Creative & Document Cloud', "drs":["ADBE03", "ADBE06"]},
    {"sym":'AFRM', "name":'Affirm Holdings, Inc.', "region":'US', "yf":"AFRM", "ind":'Buy Now Pay Later', "drs":["AFRM03"]},
    {"sym":'AMAT', "name":'Applied Materials, Inc.', "region":'US', "yf":"AMAT", "ind":'Semiconductor Equipment', "drs":["AMAT23"]},
    {"sym":'AMD', "name":'Advanced Micro Devices, Inc.', "region":'US', "yf":"AMD", "ind":'AI Chips & Processors', "drs":["AMD03", "AMD23", "AMD80"]},
    {"sym":'AMGN', "name":'Amgen Inc.', "region":'US', "yf":"AMGN", "ind":'Biotechnology', "drs":["AMGN06"]},
    {"sym":'AMZN', "name":'Amazon.com, Inc.', "region":'US', "yf":"AMZN", "ind":'E-commerce & Cloud', "drs":["AMZN01", "AMZN03", "AMZN06", "AMZN23", "AMZN80"]},
    {"sym":'ANET', "name":'Arista Networks, Inc.', "region":'US', "yf":"ANET", "ind":'Cloud Networking', "drs":["ANET23", "ANET80"]},
    {"sym":'APLD', "name":'Applied Digital Corp.', "region":'US', "yf":"APLD", "ind":'AI Data Centers', "drs":["APLD03"]},
    {"sym":'ASML', "name":'ASML Holding N.V.', "region":'US', "yf":"ASML", "ind":'Semiconductor Lithography', "drs":["ASML01"]},
    {"sym":'ASTS', "name":'AST SpaceMobile, Inc.', "region":'US', "yf":"ASTS", "ind":'Space-Based Broadband', "drs":["ASTS03"]},
    {"sym":'AVGO', "name":'Broadcom Inc.', "region":'US', "yf":"AVGO", "ind":'Semiconductors & Software', "drs":["AVGO23", "AVGO80"]},
    {"sym":'AXP', "name":'American Express Company', "region":'US', "yf":"AXP", "ind":'Financial Services', "drs":["AXP06"]},
    {"sym":'BAC', "name":'Bank of America Corp.', "region":'US', "yf":"BAC", "ind":'Commercial Banking', "drs":["BAC03"]},
    {"sym":'BDX', "name":'Becton, Dickinson and Company', "region":'US', "yf":"BDX", "ind":'Medical Devices', "drs":["BDX06"]},
    {"sym":'BKNG', "name":'Booking Holdings Inc.', "region":'US', "yf":"BKNG", "ind":'Online Travel Services', "drs":["BKNG03", "BKNG80"]},
    {"sym":'BLK', "name":'BlackRock, Inc.', "region":'US', "yf":"BLK", "ind":'Asset Management', "drs":["BLK06"]},
    {"sym":'BOEING', "name":'The Boeing Company', "region":'US', "yf":"BA", "ind":'Aerospace & Defense', "drs":["BOEING80"]},
    {"sym":'BRKB', "name":'Berkshire Hathaway Inc. B', "region":'US', "yf":"BRK-B", "ind":'Diversified Conglomerate', "drs":["BRKB23", "BRKB80"]},
    {"sym":'CCJ', "name":'Cameco Corporation', "region":'US', "yf":"CCJ", "ind":'Uranium Mining', "drs":["CCJ23"]},
    {"sym":'CEG', "name":'Constellation Energy Corp.', "region":'US', "yf":"CEG", "ind":'Clean Energy & Nuclear', "drs":["CEG23"]},
    {"sym":'CME', "name":'CME Group Inc.', "region":'US', "yf":"CME", "ind":'Financial Exchanges', "drs":["CME03"]},
    {"sym":'COHR', "name":'Coherent Corp.', "region":'US', "yf":"COHR", "ind":'Photonics & Lasers', "drs":["COHR23"]},
    {"sym":'COIN', "name":'Coinbase Global, Inc.', "region":'US', "yf":"COIN", "ind":'Crypto Exchange', "drs":["COIN23", "COIN80"]},
    {"sym":'COSTCO', "name":'Costco Wholesale Corp.', "region":'US', "yf":"COST", "ind":'Membership Retail', "drs":["COSTCO19"]},
    {"sym":'CRM', "name":'Salesforce, Inc.', "region":'US', "yf":"CRM", "ind":'CRM & Enterprise SaaS', "drs":["CRM01", "CRM06", "CRM80"]},
    {"sym":'CRSP', "name":'CRISPR Therapeutics AG', "region":'US', "yf":"CRSP", "ind":'Gene Editing', "drs":["CRSP03"]},
    {"sym":'CRWD', "name":'CrowdStrike Holdings, Inc.', "region":'US', "yf":"CRWD", "ind":'Cybersecurity AI', "drs":["CRWD06", "CRWD80"]},
    {"sym":'CRWV', "name":'CoreWeave, Inc.', "region":'US', "yf":"CRWV", "ind":'AI Cloud Infrastructure', "drs":["CRWV03"]},
    {"sym":'CSCO', "name":'Cisco Systems, Inc.', "region":'US', "yf":"CSCO", "ind":'Networking & Security', "drs":["CSCO06"]},
    {"sym":'DASH', "name":'DoorDash, Inc.', "region":'US', "yf":"DASH", "ind":'Food Delivery Platform', "drs":["DASH03"]},
    {"sym":'DDOG', "name":'Datadog, Inc.', "region":'US', "yf":"DDOG", "ind":'Cloud Monitoring & APM', "drs":["DDOG19"]},
    {"sym":'DELL', "name":'Dell Technologies Inc.', "region":'US', "yf":"DELL", "ind":'PCs & Enterprise IT', "drs":["DELL19"]},
    {"sym":'DISNEY', "name":'The Walt Disney Company', "region":'US', "yf":"DIS", "ind":'Media & Entertainment', "drs":["DISNEY19"]},
    {"sym":'DUOL', "name":'Duolingo, Inc.', "region":'US', "yf":"DUOL", "ind":'EdTech & Language Learning', "drs":["DUOL06"]},
    {"sym":'EOSE', "name":'Eos Energy Enterprises, Inc.', "region":'US', "yf":"EOSE", "ind":'Energy Storage', "drs":["EOSE03"]},
    {"sym":'ESTEE', "name":'Estee Lauder Companies Inc.', "region":'US', "yf":"EL", "ind":'Prestige Beauty', "drs":["ESTEE80"]},
    {"sym":'EXPE', "name":'Expedia Group, Inc.', "region":'US', "yf":"EXPE", "ind":'Online Travel Platform', "drs":["EXPE06"]},
    {"sym":'FCX', "name":'Freeport-McMoRan Inc.', "region":'US', "yf":"FCX", "ind":'Copper & Gold Mining', "drs":["FCX23"]},
    {"sym":'FERRARI', "name":'Ferrari N.V.', "region":'US', "yf":"RACE", "ind":'Luxury Sports Cars', "drs":["FERRARI80"]},
    {"sym":'GDS', "name":'GDS Holdings Limited', "region":'US', "yf":"GDS", "ind":'China Data Centers', "drs":["GDS23"]},
    {"sym":'GEV', "name":'GE Vernova Inc.', "region":'US', "yf":"GEV", "ind":'Clean Power Equipment', "drs":["GEV23", "GEV80"]},
    {"sym":'GIGA', "name":'GigaCloud Technology Inc.', "region":'US', "yf":"GCT", "ind":'B2B E-commerce Platform', "drs":["GIGA23"]},
    {"sym":'GOLDUS', "name":'SPDR Gold Shares ETF', "region":'US', "yf":"GLD", "ind":'Gold ETF US', "drs":["GOLDUS03", "GOLDUS19", "GOLDUS80"]},
    {"sym":'GOOG', "name":'Alphabet Inc. Class C', "region":'US', "yf":"GOOG", "ind":'Search, AI & Advertising', "drs":["GOOG23", "GOOG80"]},
    {"sym":'GOOGL', "name":'Alphabet Inc. Class A', "region":'US', "yf":"GOOGL", "ind":'Search, AI & Advertising', "drs":["GOOGL01", "GOOGL03"]},
    {"sym":'GRAB', "name":'Grab Holdings Limited', "region":'US', "yf":"GRAB", "ind":'Super App Southeast Asia', "drs":["GRAB80"]},
    {"sym":'GSUS', "name":'The Goldman Sachs Group, Inc.', "region":'US', "yf":"GS", "ind":'US Equity ETF', "drs":["GSUS06"]},
    {"sym":'HIMS', "name":'Hims & Hers Health, Inc.', "region":'US', "yf":"HIMS", "ind":'Telehealth & Wellness', "drs":["HIMS03"]},
    {"sym":'HOOD', "name":'Robinhood Markets, Inc.', "region":'US', "yf":"HOOD", "ind":'Commission-Free Trading', "drs":["HOOD03", "HOOD06", "HOOD80"]},
    {"sym":'IBM', "name":'IBM Corporation', "region":'US', "yf":"IBM", "ind":'Enterprise AI & Cloud', "drs":["IBM06"]},
    {"sym":'INTEL', "name":'Intel Corporation', "region":'US', "yf":"INTC", "ind":'Microprocessors & Foundry', "drs":["INTEL03", "INTEL23"]},
    {"sym":'IONQ', "name":'IonQ, Inc.', "region":'US', "yf":"IONQ", "ind":'Quantum Computing', "drs":["IONQ03"]},
    {"sym":'ISRG', "name":'Intuitive Surgical, Inc.', "region":'US', "yf":"ISRG", "ind":'Robotic Surgery Systems', "drs":["ISRG01", "ISRG06", "ISRG19"]},
    {"sym":'JEPI', "name":'JPMorgan Premium Income ETF', "region":'US', "yf":"JEPI", "ind":'Covered Call Income ETF', "drs":["JEPI19"]},
    {"sym":'JGRO', "name":'JPMorgan Active Growth ETF', "region":'US', "yf":"JGRO", "ind":'Active Growth ETF', "drs":["JGRO19"]},
    {"sym":'JNJ', "name":'Johnson & Johnson', "region":'US', "yf":"JNJ", "ind":'Pharmaceuticals & MedTech', "drs":["JNJ03"]},
    {"sym":'KLAC', "name":'KLA Corporation', "region":'US', "yf":"KLAC", "ind":'Semiconductor Equipment', "drs":["KLAC23"]},
    {"sym":'KO', "name":'The Coca-Cola Company', "region":'US', "yf":"KO", "ind":'Beverages', "drs":["KO80"]},
    {"sym":'LITE', "name":'Lumentum Holdings Inc.', "region":'US', "yf":"LITE", "ind":'Optical & Photonic Products', "drs":["LITE23"]},
    {"sym":'LLY', "name":'Eli Lilly and Company', "region":'US', "yf":"LLY", "ind":'Pharmaceuticals', "drs":["LLY23", "LLY80"]},
    {"sym":'LRCX', "name":'Lam Research Corporation', "region":'US', "yf":"LRCX", "ind":'Etch & Deposition Systems', "drs":["LRCX23"]},
    {"sym":'LULU', "name":'Lululemon Athletica Inc.', "region":'US', "yf":"LULU", "ind":'Athletic Apparel', "drs":["LULU06"]},
    {"sym":'MA', "name":'Mastercard Incorporated', "region":'US', "yf":"MA", "ind":'Payment Processing', "drs":["MA80"]},
    {"sym":'MELI', "name":'MercadoLibre, Inc.', "region":'US', "yf":"MELI", "ind":'Latin America E-commerce', "drs":["MELI06", "MELI23"]},
    {"sym":'META', "name":'Meta Platforms, Inc.', "region":'US', "yf":"META", "ind":'Social Media & AI', "drs":["META01", "META06", "META23", "META80"]},
    {"sym":'MICRON', "name":'Micron Technology, Inc.', "region":'US', "yf":"MU", "ind":'Memory Semiconductors', "drs":["MICRON01", "MICRON03", "MICRON19", "MICRON23", "MICRON80"]},
    {"sym":'MNSO', "name":'MINISO Group Holding Ltd.', "region":'US', "yf":"MNSO", "ind":'Value Lifestyle Retail', "drs":["MNSO80"]},
    {"sym":'MNST', "name":'Monster Beverage Corporation', "region":'US', "yf":"MNST", "ind":'Energy Drinks', "drs":["MNST06"]},
    {"sym":'MP', "name":'MP Materials Corp.', "region":'US', "yf":"MP", "ind":'Rare Earth Materials', "drs":["MP23", "MP80"]},
    {"sym":'MRVL', "name":'Marvell Technology, Inc.', "region":'US', "yf":"MRVL", "ind":'Custom AI Silicon', "drs":["MRVL06", "MRVL23", "MRVL80"]},
    {"sym":'MS', "name":'Morgan Stanley', "region":'US', "yf":"MS", "ind":'Investment Banking', "drs":["MS06"]},
    {"sym":'MSFT', "name":'Microsoft Corporation', "region":'US', "yf":"MSFT", "ind":'Software, Cloud & AI', "drs":["MSFT01", "MSFT03", "MSFT06", "MSFT19", "MSFT23", "MSFT80"]},
    {"sym":'NBIS', "name":'Nebius Group N.V.', "region":'US', "yf":"NBIS", "ind":'AI Cloud Infrastructure', "drs":["NBIS03", "NBIS23"]},
    {"sym":'NDAQ', "name":'Nasdaq, Inc.', "region":'US', "yf":"NDAQ", "ind":'Financial Exchanges', "drs":["NDAQ06"]},
    {"sym":'NEE', "name":'NextEra Energy, Inc.', "region":'US', "yf":"NEE", "ind":'Clean Energy Utilities', "drs":["NEE80"]},
    {"sym":'NEM', "name":'Newmont Corporation', "region":'US', "yf":"NEM", "ind":'Gold & Copper Mining', "drs":["NEM06", "NEM23"]},
    {"sym":'NET', "name":'Cloudflare, Inc.', "region":'US', "yf":"NET", "ind":'Network Security & CDN', "drs":["NET03"]},
    {"sym":'NFLX', "name":'Netflix, Inc.', "region":'US', "yf":"NFLX", "ind":'Entertainment Streaming', "drs":["NFLX06", "NFLX80"]},
    {"sym":'NIKE', "name":'NIKE, Inc.', "region":'US', "yf":"NKE", "ind":'Athletic Footwear & Apparel', "drs":["NIKE80"]},
    {"sym":'NOW', "name":'ServiceNow, Inc.', "region":'US', "yf":"NOW", "ind":'Enterprise SaaS Platform', "drs":["NOW19"]},
    {"sym":'NVDA', "name":'NVIDIA Corporation', "region":'US', "yf":"NVDA", "ind":'AI Chips & GPUs', "drs":["NVDA01", "NVDA03", "NVDA06", "NVDA19", "NVDA23", "NVDA80"]},
    {"sym":'NVTS', "name":'Navitas Semiconductor Corp.', "region":'US', "yf":"NVTS", "ind":'GaN Power Semiconductors', "drs":["NVTS03", "NVTS23"]},
    {"sym":'ON', "name":'ON Semiconductor Corp.', "region":'US', "yf":"ON", "ind":'Power & Signal Management', "drs":["ON23"]},
    {"sym":'ONON', "name":'On Holding AG', "region":'US', "yf":"ONON", "ind":'Performance Running Shoes', "drs":["ONON03"]},
    {"sym":'ORCL', "name":'Oracle Corporation', "region":'US', "yf":"ORCL", "ind":'Enterprise Software & DB', "drs":["ORCL01", "ORCL06", "ORCL19"]},
    {"sym":'PANW', "name":'Palo Alto Networks, Inc.', "region":'US', "yf":"PANW", "ind":'Cybersecurity Platform', "drs":["PANW80"]},
    {"sym":'PEP', "name":'PepsiCo, Inc.', "region":'US', "yf":"PEP", "ind":'Beverages & Snack Foods', "drs":["PEP80"]},
    {"sym":'PFIZER', "name":'Pfizer Inc.', "region":'US', "yf":"PFE", "ind":'Biopharmaceuticals', "drs":["PFIZER19"]},
    {"sym":'PLTR', "name":'Palantir Technologies Inc.', "region":'US', "yf":"PLTR", "ind":'AI & Big Data Analytics', "drs":["PLTR01", "PLTR03", "PLTR06", "PLTR23"]},
    {"sym":'PYPL', "name":'PayPal Holdings, Inc.', "region":'US', "yf":"PYPL", "ind":'Digital Payments', "drs":["PYPL06"]},
    {"sym":'QCOM', "name":'Qualcomm Inc.', "region":'US', "yf":"QCOM", "ind":'Wireless Semiconductors', "drs":["QCOM06"]},
    {"sym":'QQQM', "name":'Invesco Nasdaq 100 ETF', "region":'US', "yf":"QQQM", "ind":'Nasdaq 100 ETF', "drs":["QQQM19"]},
    {"sym":'RBLX', "name":'Roblox Corporation', "region":'US', "yf":"RBLX", "ind":'Metaverse Gaming Platform', "drs":["RBLX06"]},
    {"sym":'REMX', "name":'VanEck Rare Earth ETF', "region":'US', "yf":"REMX", "ind":'Rare Earth Metals ETF', "drs":["REMX03"]},
    {"sym":'RGTI', "name":'Rigetti Computing, Inc.', "region":'US', "yf":"RGTI", "ind":'Quantum Computing', "drs":["RGTI03"]},
    {"sym":'RKLB', "name":'Rocket Lab USA, Inc.', "region":'US', "yf":"RKLB", "ind":'Space Systems & Aerospace', "drs":["RKLB03", "RKLB23", "RKLB80"]},
    {"sym":'SBUX', "name":'Starbucks Corporation', "region":'US', "yf":"SBUX", "ind":'Global Coffeehouse Chain', "drs":["SBUX80"]},
    {"sym":'SEAGATE', "name":'Seagate Technology Holdings', "region":'US', "yf":"STX", "ind":'Hard Disk Drives & Storage', "drs":["SEAGATE23"]},
    {"sym":'SHOP', "name":'Shopify Inc.', "region":'US', "yf":"SHOP", "ind":'E-commerce Platform', "drs":["SHOP03", "SHOP06"]},
    {"sym":'SIL', "name":'Global X Silver Miners ETF', "region":'US', "yf":"SIL", "ind":'Silver Mining ETF', "drs":["SIL03"]},
    {"sym":'SMCI', "name":'Super Micro Computer, Inc.', "region":'US', "yf":"SMCI", "ind":'AI Server Systems', "drs":["SMCI03"]},
    {"sym":'SNDK', "name":'SanDisk Corporation', "region":'US', "yf":"SNDK", "ind":'Flash Storage Solutions', "drs":["SNDK03", "SNDK23", "SNDK80"]},
    {"sym":'SNOW', "name":'Snowflake Inc.', "region":'US', "yf":"SNOW", "ind":'Cloud Data Platform', "drs":["SNOW06", "SNOW23"]},
    {"sym":'SOFI', "name":'SoFi Technologies, Inc.', "region":'US', "yf":"SOFI", "ind":'Digital Financial Services', "drs":["SOFI23"]},
    {"sym":'SP500US', "name":'SPDR Portfolio S&P 500 ETF', "region":'US', "yf":"SPYM", "ind":'S&P 500 ETF', "drs":["SP500US19", "SP500US80"]},
    {"sym":'SPBOND', "name":'SPDR Portfolio Aggregate Bond ETF', "region":'US', "yf":"SPAB", "ind":'Bond ETF', "drs":["SPBOND80"]},
    {"sym":'SPCOM', "name":'SPDR Communication Svc ETF', "region":'US', "yf":"XLC", "ind":'Comm Services ETF', "drs":["SPCOM80"]},
    {"sym":'SPENGY', "name":'SPDR Energy Sector ETF', "region":'US', "yf":"XLE", "ind":'Energy Sector ETF', "drs":["SPENGY80"]},
    {"sym":'SPFIN', "name":'SPDR Financial Sector ETF', "region":'US', "yf":"XLF", "ind":'Financial Sector ETF', "drs":["SPFIN80"]},
    {"sym":'SPHLTH', "name":'SPDR Healthcare Sector ETF', "region":'US', "yf":"XLV", "ind":'Healthcare Sector ETF', "drs":["SPHLTH80"]},
    {"sym":'SPOT', "name":'Spotify Technology S.A.', "region":'US', "yf":"SPOT", "ind":'Music Streaming', "drs":["SPOT06"]},
    {"sym":'SPTECH', "name":'SPDR Technology Sector ETF', "region":'US', "yf":"XLK", "ind":'Technology Sector ETF', "drs":["SPTECH80"]},
    {"sym":'SYNP', "name":'Synopsys, Inc.', "region":'US', "yf":"SNPS", "ind":'EDA & IP Software', "drs":["SYNP03", "SYNP23"]},
    {"sym":'TEL', "name":'TE Connectivity Ltd.', "region":'US', "yf":"TEL", "ind":'Connectivity & Sensors', "drs":["TEL23", "TEL80"]},
    {"sym":'TER', "name":'Teradyne, Inc.', "region":'US', "yf":"TER", "ind":'Automated Test Equipment', "drs":["TER23"]},
    {"sym":'TME', "name":'Tencent Music Entertainment', "region":'US', "yf":"TME", "ind":'Music Streaming China', "drs":["TME23"]},
    {"sym":'TRIPCOM', "name":'Trip.com Group Limited', "region":'US', "yf":"TCOM", "ind":'Online Travel China', "drs":["TRIPCOM23", "TRIPCOM80"]},
    {"sym":'TRVUS', "name":'Travelers Companies, Inc.', "region":'US', "yf":"TRV", "ind":'Buffered Return ETF', "drs":["TRVUS06"]},
    {"sym":'TSLA', "name":'Tesla, Inc.', "region":'US', "yf":"TSLA", "ind":'Electric Vehicles & Energy', "drs":["TSLA01", "TSLA03", "TSLA23", "TSLA80"]},
    {"sym":'UBER', "name":'Uber Technologies, Inc.', "region":'US', "yf":"UBER", "ind":'Ride-Hailing & Delivery', "drs":["UBER06"]},
    {"sym":'UNH', "name":'UnitedHealth Group Inc.', "region":'US', "yf":"UNH", "ind":'Health Insurance & Services', "drs":["UNH19"]},
    {"sym":'USTR', "name":'US Treasury Bond ETF', "region":'HK', "yf":"3450.HK", "ind":'US Treasury ETF', "drs":["USTR24"]},
    {"sym":'VISA', "name":'Visa Inc.', "region":'US', "yf":"V", "ind":'Payment Technology', "drs":["VISA06", "VISA80"]},
    {"sym":'VRT', "name":'Vertiv Holdings Co', "region":'US', "yf":"VRT", "ind":'Data Center Infrastructure', "drs":["VRT23"]},
    {"sym":'VT', "name":'Vanguard Total World ETF', "region":'US', "yf":"VT", "ind":'Global Equity ETF', "drs":["VT03"]},
    {"sym":'WMT', "name":'Walmart Inc.', "region":'US', "yf":"WMT", "ind":'Omnichannel Retail', "drs":["WMT06"]},
    {"sym":'WORLD', "name":'CSOP World ETF (HK)', "region":'HK', "yf":"3422.HK", "ind":'Global Equity ETF', "drs":["WORLD03"]},
    {"sym":'WORLDA', "name":'iShares MSCI World ETF (Milan)', "region":'EU', "yf":"SMSWLD.MI", "ind":'Global Equity ETF', "drs":["WORLDA01"]},
    # ── Hong Kong / China ──────────────────────────────────────────────────
    {"sym":'AIA', "name":'AIA Group Limited', "region":'HK', "yf":"1299.HK", "ind":'Life Insurance APAC', "drs":["AIA06", "AIA19", "AIA23"]},
    {"sym":'ANTA', "name":'Anta Sports Products Ltd.', "region":'HK', "yf":"2020.HK", "ind":'Sportswear & Footwear', "drs":["ANTA13", "ANTA23"]},
    {"sym":'ASEMI', "name":'Asia Semiconductor ETF', "region":'HK', "yf":"3119.HK", "ind":'Asia Semiconductor ETF', "drs":["ASEMI23", "ASEMI24"]},
    {"sym":'BABA', "name":'Alibaba Group Holding Ltd.', "region":'HK', "yf":"9988.HK", "ind":'E-commerce & Cloud', "drs":["BABA01", "BABA06", "BABA13", "BABA23", "BABA80"]},
    {"sym":'BIDU', "name":'Baidu, Inc.', "region":'HK', "yf":"9888.HK", "ind":'AI & Chinese Search', "drs":["BIDU01", "BIDU06", "BIDU23", "BIDU80"]},
    {"sym":'BILIBILI', "name":'Bilibili Inc.', "region":'HK', "yf":"9626.HK", "ind":'Online Video & Gaming', "drs":["BILIBILI01"]},
    {"sym":'BIREN', "name":'Shanghai Biren Tech Co., Ltd.', "region":'HK', "yf":"6082.HK", "ind":'AI GPU Chips China', "drs":["BIREN23"]},
    {"sym":'BYDCOM', "name":'BYD Company Limited', "region":'HK', "yf":"1211.HK", "ind":'EV & Battery Manufacturing', "drs":["BYDCOM01", "BYDCOM80"]},
    {"sym":'CAMBRI', "name":'Cambridge Industries Group', "region":'HK', "yf":"688256.SS", "ind":'Auto Components AI', "drs":["CAMBRI80"]},
    {"sym":'CATL', "name":'Contemporary Amperex Technology', "region":'HK', "yf":"3750.HK", "ind":'EV Battery Systems', "drs":["CATL01", "CATL23", "CATL80"]},
    {"sym":'CHHONGQ', "name":'Chongqing Changan Automobile', "region":'HK', "yf":"000625.SZ", "ind":'Automotive China', "drs":["CHHONGQ19"]},
    {"sym":'CHMOBILE', "name":'China Mobile Limited', "region":'HK', "yf":"0941.HK", "ind":'Telecom Services China', "drs":["CHMOBILE19", "CHMOBILE23"]},
    {"sym":'CHNXT', "name":'CSOP China NextGen ETF', "region":'HK', "yf":"159682.SZ", "ind":'China Next-Gen Leaders ETF', "drs":["CHNXT5023"]},
    {"sym":'CMBANK', "name":'China Merchants Bank', "region":'HK', "yf":"3968.HK", "ind":'Commercial Banking China', "drs":["CMBANK23"]},
    {"sym":'CN', "name":'CSI 300 Index ETF (HK)', "region":'HK', "yf":"3188.HK", "ind":'China Broad Market ETF', "drs":["CN01", "CN23"]},
    {"sym":'CNBIO', "name":'China Biotech ETF', "region":'HK', "yf":"2820.HK", "ind":'China Biotech ETF', "drs":["CNBIO24"]},
    {"sym":'CNEV', "name":'China EV & Battery ETF', "region":'HK', "yf":"3145.HK", "ind":'China EV ETF', "drs":["CNEV24"]},
    {"sym":'CNRE', "name":'China Resources Enterprise', "region":'HK', "yf":"0291.HK", "ind":'Diversified Resources China', "drs":["CNRE80"]},
    {"sym":'CNROBOAI', "name":'China Robotics & AI ETF', "region":'HK', "yf":"3193.HK", "ind":'China Robotics ETF', "drs":["CNROBOAI23"]},
    {"sym":'CNSEMI', "name":'China Semiconductor ETF', "region":'HK', "yf":"3191.HK", "ind":'China Semiconductor ETF', "drs":["CNSEMI23"]},
    {"sym":'CNSTAR', "name":'China AMC SSE STAR 50 ETF', "region":'HK', "yf":"588000.SS", "ind":'China STAR Market ETF', "drs":["CNSTAR5023"]},
    {"sym":'CNTECH', "name":'HS China Technology ETF', "region":'HK', "yf":"3088.HK", "ind":'China Technology ETF', "drs":["CNTECH01"]},
    {"sym":'CYPC', "name":'China Yangtze Power', "region":'HK', "yf":"600900.SS", "ind":'Hydropower China', "drs":["CYPC80"]},
    {"sym":'GAC', "name":'Guangzhou Automobile Group', "region":'HK', "yf":"2238.HK", "ind":'Automotive Group China', "drs":["GAC03"]},
    {"sym":'GANFENG', "name":'Ganfeng Lithium Group', "region":'HK', "yf":"1772.HK", "ind":'Lithium Mining & Refining', "drs":["GANFENG23"]},
    {"sym":'GEELY', "name":'Geely Automobile Holdings', "region":'HK', "yf":"0175.HK", "ind":'Smart EVs China', "drs":["GEELY06", "GEELY80"]},
    {"sym":'GOLD', "name":'SPDR Gold ETF (HK)', "region":'HK', "yf":"2840.HK", "ind":'Gold ETF (HK)', "drs":["GOLD03", "GOLD19"]},
    {"sym":'GSEMI', "name":'Global X Semiconductor ETF', "region":'JP', "yf":"2243.T", "ind":'Semiconductor ETF HK', "drs":["GSEMI24"]},
    {"sym":'HAIERS', "name":'Haier Smart Home Co., Ltd.', "region":'HK', "yf":"6690.HK", "ind":'Home Appliances AI', "drs":["HAIERS19"]},
    {"sym":'HANSOH', "name":'Hansoh Pharmaceutical Group', "region":'HK', "yf":"3692.HK", "ind":'Pharmaceuticals China', "drs":["HANSOH19"]},
    {"sym":'HK', "name":'Hang Seng ETF (Tracker Fund)', "region":'HK', "yf":"2800.HK", "ind":'HK Broad Market ETF', "drs":["HK01", "HK13"]},
    {"sym":'HKCE', "name":'HSCEI ETF (China Enterprises)', "region":'HK', "yf":"2828.HK", "ind":'China Enterprise ETF', "drs":["HKCE01"]},
    {"sym":'HKEX', "name":'HK Exchanges & Clearing Ltd.', "region":'HK', "yf":"0388.HK", "ind":'Financial Exchange HK', "drs":["HKEX23"]},
    {"sym":'HKTECH', "name":'Hang Seng TECH Index ETF', "region":'HK', "yf":"3032.HK", "ind":'HK Tech ETF', "drs":["HKTECH13"]},
    {"sym":'HORIZON', "name":'Horizon Robotics, Inc.', "region":'HK', "yf":"9660.HK", "ind":'Automotive AI Chips', "drs":["HORIZON23"]},
    {"sym":'HSHD', "name":'Hang Seng High Dividend ETF', "region":'HK', "yf":"3110.HK", "ind":'HK High Dividend ETF', "drs":["HSHD23"]},
    {"sym":'HUAHONG', "name":'Hua Hong Semiconductor', "region":'HK', "yf":"1347.HK", "ind":'Foundry Services China', "drs":["HUAHONG23"]},
    {"sym":'ICBC', "name":'Industrial & Commercial Bank', "region":'HK', "yf":"1398.HK", "ind":'State Banking China', "drs":["ICBC06", "ICBC19"]},
    {"sym":'IFLYTEK', "name":'iFLYTEK Co., Ltd.', "region":'HK', "yf":"002230.SZ", "ind":'AI Voice Technology', "drs":["IFLYTEK80"]},
    {"sym":'INDIA', "name":'CSOP India Technology ETF', "region":'HK', "yf":"3404.HK", "ind":'India Technology ETF', "drs":["INDIA01"]},
    {"sym":'JAP', "name":'CSOP Japan ETF', "region":'HK', "yf":"3150.HK", "ind":'Japan Market ETF (HK)', "drs":["JAP03"]},
    {"sym":'JAPAN1000', "name":'HS Japan Topix 100 IDX ETF', "region":'HK', "yf":"3410.HK", "ind":'Japan Topix 100 ETF (HK)', "drs":["JAPAN10001"]},
    {"sym":'JAPAN', "name":'ChinaAMC MSCI Japan Hedged to USD ETF', "region":'HK', "yf":"3160.HK", "ind":'Japan MSCI Hedged ETF (HK)', "drs":["JAPAN13"]},
    {"sym":'JD', "name":'JD.com, Inc.', "region":'HK', "yf":"9618.HK", "ind":'E-commerce Logistics China', "drs":["JD80"]},
    {"sym":'JDHEAL', "name":'JD Health International Inc.', "region":'HK', "yf":"6618.HK", "ind":'Healthcare E-commerce', "drs":["JDHEAL19"]},
    {"sym":'JLMAG', "name":'JL Mag Rare-Earth Co., Ltd.', "region":'HK', "yf":"6680.HK", "ind":'Rare Earth Magnets', "drs":["JLMAG80"]},
    {"sym":'KINGSOFT', "name":'Kingsoft Corporation Limited', "region":'HK', "yf":"3888.HK", "ind":'Software & Cloud China', "drs":["KINGSOFT23"]},
    {"sym":'KUAISH', "name":'Kuaishou Technology', "region":'HK', "yf":"1024.HK", "ind":'Short-Video Platform China', "drs":["KUAISH01", "KUAISH06", "KUAISH23", "KUAISH80"]},
    {"sym":'LENOVO', "name":'Lenovo Group Limited', "region":'HK', "yf":"0992.HK", "ind":'PCs & Smart Devices', "drs":["LENOVO13"]},
    {"sym":'LPGOLD', "name":'Laopu Gold / LP Gold ETF', "region":'HK', "yf":"6181.HK", "ind":'Gold-related HK', "drs":["LPGOLD13"]},
    {"sym":'MAOGEP', "name":'Mao Geping Cosmetics Co.', "region":'HK', "yf":"1318.HK", "ind":'Premium Cosmetics China', "drs":["MAOGEP80"]},
    {"sym":'MEITUAN', "name":'Meituan', "region":'HK', "yf":"3690.HK", "ind":'Food Delivery & Local Services', "drs":["MEITUAN19", "MEITUAN23", "MEITUAN80"]},
    {"sym":'MIDEA', "name":'Midea Group Co., Ltd.', "region":'HK', "yf":"000333.SZ", "ind":'Home Appliances China', "drs":["MIDEA80"]},
    {"sym":'MIXUE', "name":'Mixue Group', "region":'HK', "yf":"2097.HK", "ind":'Budget Ice Cream & Tea', "drs":["MIXUE80"]},
    {"sym":'MONTAGE', "name":'Montage Technology Co.', "region":'HK', "yf":"688100.SS", "ind":'Memory Interface ICs', "drs":["MONTAGE80"]},
    {"sym":'MOUTAI', "name":'Kweichow Moutai Co., Ltd.', "region":'HK', "yf":"600519.SS", "ind":'Premium Baijiu Distiller', "drs":["MOUTAI80"]},
    {"sym":'NAURA', "name":'NAURA Technology Group', "region":'HK', "yf":"002371.SZ", "ind":'Semiconductor Equipment', "drs":["NAURA23", "NAURA80"]},
    {"sym":'NDX', "name":'CSOP Nasdaq-100 ETF (HK)', "region":'HK', "yf":"3086.HK", "ind":'Nasdaq 100 ETF (HK)', "drs":["NDX01"]},
    {"sym":'NETEASE', "name":'NetEase, Inc.', "region":'HK', "yf":"9999.HK", "ind":'Internet & Online Gaming', "drs":["NETEASE80"]},
    {"sym":'NONGFU', "name":'Nongfu Spring Co., Ltd.', "region":'HK', "yf":"9633.HK", "ind":'Bottled Water & Beverages', "drs":["NONGFU80"]},
    {"sym":'OIL', "name":'CSOP Crude Oil ETF', "region":'HK', "yf":"3097.HK", "ind":'Crude Oil ETF (HK)', "drs":["OIL03", "OIL24"]},
    {"sym":'PETROCN', "name":'PetroChina Company Limited', "region":'HK', "yf":"0857.HK", "ind":'Oil & Gas China', "drs":["PETROCN80"]},
    {"sym":'PINGAN', "name":'Ping An Insurance Group', "region":'HK', "yf":"2318.HK", "ind":'Financial & Insurance', "drs":["PINGAN01", "PINGAN80"]},
    {"sym":'POPMART', "name":'Pop Mart International Group', "region":'HK', "yf":"9992.HK", "ind":'Collectible Toys & IP', "drs":["POPMART23", "POPMART80"]},
    {"sym":'SENSE', "name":'SenseTime Group Inc.', "region":'HK', "yf":"0020.HK", "ind":'AI & Computer Vision', "drs":["SENSE23"]},
    {"sym":'SINOBIO', "name":'Sino Biopharmaceutical', "region":'HK', "yf":"1177.HK", "ind":'Biopharmaceuticals China', "drs":["SINOBIO19"]},
    {"sym":'SMIC', "name":'SMIC (Semiconductor Mfg. Intl)', "region":'HK', "yf":"0981.HK", "ind":'Foundry Services China', "drs":["SMIC01", "SMIC03", "SMIC13", "SMIC23"]},
    {"sym":'SP', "name":'CSOP S&P 500 ETF (HK)', "region":'HK', "yf":"3195.HK", "ind":'S&P 500 ETF (HK)', "drs":["SP50001"]},
    {"sym":'STAR', "name":'CSOP STAR 50 ETF (HK)', "region":'HK', "yf":"3151.HK", "ind":'STAR Market ETF (HK)', "drs":["STAR5001"]},
    {"sym":'STEG', "name":'Shanghai Electric Group', "region":'HK', "yf":"2727.HK", "ind":'Industrial Energy Equipment', "drs":["STEG19"]},
    {"sym":'SUNNY', "name":'Sunny Optical Technology', "region":'HK', "yf":"2382.HK", "ind":'Optics & Camera Modules', "drs":["SUNNY19", "SUNNY80"]},
    {"sym":'TENCENT', "name":'Tencent Holdings Limited', "region":'HK', "yf":"0700.HK", "ind":'Internet & Gaming China', "drs":["TENCENT01", "TENCENT06", "TENCENT13", "TENCENT19", "TENCENT23", "TENCENT80"]},
    {"sym":'UBTECH', "name":'UBTECH Robotics Corp.', "region":'HK', "yf":"9880.HK", "ind":'Humanoid Robotics', "drs":["UBTECH23"]},
    {"sym":'WUXI', "name":'WuXi Biologics (Cayman) Inc.', "region":'HK', "yf":"2269.HK", "ind":'Biologics CDMO', "drs":["WUXI06", "WUXI13"]},
    {"sym":'WUXIAT', "name":'WuXi AppTec Co., Ltd.', "region":'HK', "yf":"2359.HK", "ind":'Pharma R&D Services', "drs":["WUXIAT80"]},
    {"sym":'XIAOMI', "name":'Xiaomi Corporation', "region":'HK', "yf":"1810.HK", "ind":'Consumer Electronics & EVs', "drs":["XIAOMI01", "XIAOMI13", "XIAOMI19", "XIAOMI23", "XIAOMI80"]},
    {"sym":'XPENG', "name":'XPeng Inc.', "region":'HK', "yf":"9868.HK", "ind":'Smart EVs China', "drs":["XPENG03"]},
    {"sym":'ZAI', "name":'Zai Lab Limited', "region":'HK', "yf":"9688.HK", "ind":'Oncology Biotech', "drs":["ZAI23"]},
    {"sym":'ZIJIN', "name":'Zijin Mining Group', "region":'HK', "yf":"2899.HK", "ind":'Gold & Copper Mining', "drs":["ZIJIN13", "ZIJIN23", "ZIJIN80"]},
    {"sym":'ZJINNO', "name":'Zhongji Innolight Co.', "region":'HK', "yf":"300308.SZ", "ind":'Optical Transceivers', "drs":["ZJINNO80"]},
    # ── Japan ──────────────────────────────────────────────────────────────
    {"sym":'ASICS', "name":'ASICS Corporation', "region":'JP', "yf":"7936.T", "ind":'Sportswear & Running Shoes', "drs":["ASICS23"]},
    {"sym":'DISCO', "name":'DISCO Corporation', "region":'JP', "yf":"6146.T", "ind":'Precision Cutting Systems', "drs":["DISCO24"]},
    {"sym":'FANUC', "name":'FANUC Corporation', "region":'JP', "yf":"6954.T", "ind":'Factory Automation & Robots', "drs":["FANUC23"]},
    {"sym":'HITACHI', "name":'Hitachi, Ltd.', "region":'JP', "yf":"6501.T", "ind":'Digital Infrastructure', "drs":["HITACHI24"]},
    {"sym":'HONDA', "name":'Honda Motor Co., Ltd.', "region":'JP', "yf":"7267.T", "ind":'Automobiles & Motorcycles', "drs":["HONDA19"]},
    {"sym":'ITOCHU', "name":'ITOCHU Corporation', "region":'JP', "yf":"8001.T", "ind":'Diversified Trading House', "drs":["ITOCHU19"]},
    {"sym":'JPANIME', "name":'Global X Japan Games & Animation ETF', "region":'JP', "yf":"2640.T", "ind":'Japan Anime Thematic ETF', "drs":["JPANIME24"]},
    {"sym":'JPMUS', "name":'Avex Group Holdings / JP Music', "region":'JP', "yf":"7860.T", "ind":'Music & Entertainment Japan', "drs":["JPMUS06", "JPMUS19"]},
    {"sym":'JPROBOAI', "name":'Global X Japan Robotics & AI ETF', "region":'JP', "yf":"2638.T", "ind":'Japan Robotics ETF', "drs":["JPROBOAI24"]},
    {"sym":'JPSEMI', "name":'Global X Japan Semiconductor ETF', "region":'JP', "yf":"2644.T", "ind":'Japan Semiconductor ETF', "drs":["JPSEMI24"]},
    {"sym":'JTEK', "name":'Japan Technology ETF', "region":'JP', "yf":"1545.T", "ind":'Japan Technology ETF', "drs":["JTEK19"]},
    {"sym":'KEYENCE', "name":'KEYENCE Corporation', "region":'JP', "yf":"6861.T", "ind":'Factory Automation Sensors', "drs":["KEYENCE23"]},
    {"sym":'KIOXIA', "name":'Kioxia Holdings Corporation', "region":'JP', "yf":"285A.T", "ind":'NAND Flash Memory', "drs":["KIOXIA23"]},
    {"sym":'KONAMI', "name":'Konami Group Corporation', "region":'JP', "yf":"9766.T", "ind":'Video Games & Arcades', "drs":["KONAMI24"]},
    {"sym":'MITSU', "name":'Mitsubishi Corporation', "region":'JP', "yf":"8058.T", "ind":'Diversified Trading House', "drs":["MITSU19"]},
    {"sym":'MUFG', "name":'Mitsubishi UFJ Financial Group', "region":'JP', "yf":"8306.T", "ind":'Banking & Financial Services', "drs":["MUFG19", "MUFG23"]},
    {"sym":'NIKKEI', "name":'Nikkei 225 Index ETF', "region":'JP', "yf":"1321.T", "ind":'Japan Broad Market ETF', "drs":["NIKKEI80"]},
    {"sym":'NINTENDO', "name":'Nintendo Co., Ltd.', "region":'JP', "yf":"7974.T", "ind":'Video Games & Consoles', "drs":["NINTENDO19", "NINTENDO23"]},
    {"sym":'SANRIO', "name":'Sanrio Company, Ltd.', "region":'JP', "yf":"8136.T", "ind":'Character Entertainment', "drs":["SANRIO23", "SANRIO80"]},
    {"sym":'SMFG', "name":'Sumitomo Mitsui Financial Grp', "region":'JP', "yf":"8316.T", "ind":'Banking & Securities Japan', "drs":["SMFG19"]},
    {"sym":'SOFTBANK', "name":'SoftBank Group Corp.', "region":'JP', "yf":"9984.T", "ind":'Tech Investment & Telecom', "drs":["SOFTBANK23", "SOFTBANK80"]},
    {"sym":'SONY', "name":'Sony Group Corporation', "region":'JP', "yf":"6758.T", "ind":'Electronics & Entertainment', "drs":["SONY80"]},
    {"sym":'SUSHI', "name":'Food & Life Companies (Sushiro)', "region":'JP', "yf":"3563.T", "ind":'Conveyor-belt Sushi Chain', "drs":["SUSHI23"]},
    {"sym":'TOYOTA', "name":'Toyota Motor Corporation', "region":'JP', "yf":"7203.T", "ind":'Automotive Group', "drs":["TOYOTA80"]},
    {"sym":'UNIQLO', "name":'Fast Retailing Co. (UNIQLO)', "region":'JP', "yf":"9983.T", "ind":'Fast Fashion Retail', "drs":["UNIQLO80"]},
    # ── Europe ─────────────────────────────────────────────────────────────
    {"sym":'HERMES', "name":'Hermes International S.A.', "region":'EU', "yf":"RMS.PA", "ind":'Luxury Fashion & Leather Goods', "drs":["HERMES80"]},
    {"sym":'LOREAL', "name":"L'Oreal S.A.", "region":'EU', "yf":"OR.PA", "ind":'Beauty & Personal Care', "drs":["LOREAL80"]},
    {"sym":'LVMH', "name":'LVMH Moet Hennessy Louis Vuitton', "region":'EU', "yf":"MC.PA", "ind":'Luxury Goods Conglomerate', "drs":["LVMH01"]},
    {"sym":'NOVOB', "name":'Novo Nordisk A/S', "region":'EU', "yf":"NVO", "ind":'Diabetes & Obesity Drugs', "drs":["NOVOB80"]},
    {"sym":'SANOFI', "name":'Sanofi S.A.', "region":'EU', "yf":"SNY", "ind":'Pharmaceuticals EU', "drs":["SANOFI80"]},
    # ── Singapore / ASEAN ───────────────────────────────────────────────────
    {"sym":'BONDAS', "name":'iShares JPM USD Asia Credit Bond ETF', "region":'SG', "yf":"N6M.SI", "ind":'ASEAN Bond ETF', "drs":["BONDAS19"]},
    {"sym":'DBS', "name":'DBS Group Holdings Ltd.', "region":'SG', "yf":"D05.SI", "ind":'Banking Singapore', "drs":["DBS19"]},
    {"sym":'INDIAESG', "name":'iShares MSCI India Climate Transition ETF', "region":'SG', "yf":"QK9.SI", "ind":'India ESG ETF', "drs":["INDIAESG19"]},
    {"sym":'SEMB', "name":'Sembcorp Industries Ltd.', "region":'SG', "yf":"U96.SI", "ind":'Utilities & Industrials SG', "drs":["SEMB19"]},
    {"sym":'SGX', "name":'Singapore Exchange Limited', "region":'SG', "yf":"S68.SI", "ind":'Financial Exchange SG', "drs":["SGX19"]},
    {"sym":'SIA', "name":'Singapore Airlines Ltd.', "region":'SG', "yf":"C6L.SI", "ind":'Premium Aviation SG', "drs":["SIA19"]},
    {"sym":'SINGTEL', "name":'Singtel Group', "region":'SG', "yf":"Z74.SI", "ind":'Telecom Group Singapore', "drs":["SINGTEL80"]},
    {"sym":'THAIBEV', "name":'Thai Beverage Public Co.', "region":'SG', "yf":"Y92.SI", "ind":'Beverages & F&B Thailand', "drs":["THAIBEV19"]},
    {"sym":'UOB', "name":'United Overseas Bank Limited', "region":'SG', "yf":"U11.SI", "ind":'Banking Singapore', "drs":["UOB19"]},
    {"sym":'VENTURE', "name":'Venture Corporation Limited', "region":'SG', "yf":"V03.SI", "ind":'Electronics Manufacturing SG', "drs":["VENTURE19"]},
    # ── Vietnam ────────────────────────────────────────────────────────────
    {"sym":'E1VFVN', "name":'VFMVN30 ETF', "region":'VN', "yf":"E1VFVN30.VN", "ind":'Vietnam VN30 Index ETF', "drs":["E1VFVN3001"]},
    {"sym":'FPTVN', "name":'FPT Corporation', "region":'VN', "yf":"FPT.VN", "ind":'Technology Vietnam', "drs":["FPTVN11", "FPTVN19"]},
    {"sym":'FUEVFVND', "name":'VN Diamond ETF', "region":'VN', "yf":"FUEVFVND.VN", "ind":'Vietnam Diamond ETF', "drs":["FUEVFVND01"]},
    {"sym":'GASVN', "name":'PetroVietnam Gas Corp.', "region":'VN', "yf":"GAS.VN", "ind":'Natural Gas Vietnam', "drs":["GASVN11"]},
    {"sym":'HPG', "name":'Hoa Phat Group', "region":'VN', "yf":"HPG.VN", "ind":'Steel Manufacturing Vietnam', "drs":["HPG19"]},
    {"sym":'MSN', "name":'Masan Group Corporation', "region":'VN', "yf":"MSN.VN", "ind":'FMCG & Resources Vietnam', "drs":["MSN11", "MSN19"]},
    {"sym":'MWG', "name":'Mobile World Investment Group', "region":'VN', "yf":"MWG.VN", "ind":'Electronics Retail Vietnam', "drs":["MWG11", "MWG19"]},
    {"sym":'VCB', "name":'Vietcombank', "region":'VN', "yf":"VCB.VN", "ind":'Banking Vietnam', "drs":["VCB11", "VCB19"]},
    {"sym":'VHM', "name":'Vinhomes JSC', "region":'VN', "yf":"VHM.VN", "ind":'Real Estate Vietnam', "drs":["VHM19"]},
    {"sym":'VNFIN', "name":'VN Finance Leader ETF', "region":'VN', "yf":"FUESSVFL.VN", "ind":'Vietnam Finance ETF', "drs":["VNFIN24"]},
    {"sym":'VNM', "name":'Vinamilk (Vietnam Dairy)', "region":'VN', "yf":"VNM.VN", "ind":'Dairy Products Vietnam', "drs":["VNM19"]},
    # ── Taiwan ─────────────────────────────────────────────────────────────
    {"sym":'ADVANT', "name":'Advantech Co., Ltd.', "region":'TW', "yf":"2395.TW", "ind":'Industrial IoT & Edge AI', "drs":["ADVANT19", "ADVANT23"]},
    {"sym":'TAIWAN', "name":'Taiwan 50 ETF', "region":'TW', "yf":"0050.TW", "ind":'Taiwan Broad Market ETF', "drs":["TAIWAN19"]},
    {"sym":'TAIWANAI', "name":'Fubon MSCI Taiwan AI ETF', "region":'TW', "yf":"00952.TW", "ind":'Taiwan AI Thematic ETF', "drs":["TAIWANAI13"]},
    {"sym":'TAIWANHD', "name":'SPDR Taiwan High-Div ETF', "region":'TW', "yf":"00915.TW", "ind":'Taiwan High Dividend ETF', "drs":["TAIWANHD13"]},
]

